"""CI/CD integration commands."""
from __future__ import annotations

import os
import sys
from pathlib import Path

import typer
from rich import print as rprint

from ..utils.formatter import fmt

ci_app = typer.Typer(name="ci", help="CI/CD integration commands", no_args_is_help=True)


def _detect_platform() -> str | None:
    if Path(".github").exists():
        return "github"
    if Path(".gitlab-ci.yml").exists():
        return "gitlab"
    if Path(".circleci").exists():
        return "circleci"
    return None


def _github_template(with_backend: bool) -> str:
    yaml = """# Generated by: rafter ci init
name: Rafter Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rafter CLI
        run: pip install rafter-cli

      - name: Scan for secrets
        run: rafter scan local . --quiet
"""
    if with_backend:
        yaml += """
  security-audit:
    runs-on: ubuntu-latest
    needs: secret-scan
    steps:
      - uses: actions/checkout@v4

      - name: Install Rafter CLI
        run: pip install rafter-cli

      - name: Run security audit
        env:
          RAFTER_API_KEY: ${{ secrets.RAFTER_API_KEY }}
        run: rafter run --format json --quiet
"""
    return yaml


def _gitlab_template(with_backend: bool) -> str:
    yaml = """# Generated by: rafter ci init
stages:
  - security

secret-scan:
  stage: security
  image: python:3.12
  script:
    - pip install rafter-cli
    - rafter scan local . --quiet
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
"""
    if with_backend:
        yaml += """
security-audit:
  stage: security
  image: python:3.12
  needs: [secret-scan]
  script:
    - pip install rafter-cli
    - rafter run --format json --quiet
  variables:
    RAFTER_API_KEY: $RAFTER_API_KEY
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
"""
    return yaml


def _circleci_template(with_backend: bool) -> str:
    yaml = """# Generated by: rafter ci init
version: 2.1

jobs:
  secret-scan:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Rafter CLI
          command: pip install rafter-cli
      - run:
          name: Scan for secrets
          command: rafter scan local . --quiet
"""
    if with_backend:
        yaml += """
  security-audit:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Rafter CLI
          command: pip install rafter-cli
      - run:
          name: Run security audit
          command: rafter run --format json --quiet
"""

    yaml += """
workflows:
  security:
    jobs:
      - secret-scan"""

    if with_backend:
        yaml += """
      - security-audit:
          requires:
            - secret-scan"""

    yaml += "\n"
    return yaml


_GENERATORS = {
    "github": (_github_template, ".github/workflows/rafter-security.yml"),
    "gitlab": (_gitlab_template, ".gitlab-ci-rafter.yml"),
    "circleci": (_circleci_template, ".circleci/rafter-security.yml"),
}


@ci_app.command("init")
def ci_init(
    platform: str = typer.Option(None, "--platform", help="github, gitlab, or circleci (default: auto-detect)"),
    output: str = typer.Option(None, "--output", help="Output file path"),
    with_backend: bool = typer.Option(False, "--with-backend", help="Include backend security audit job"),
):
    """Generate CI/CD pipeline config for secret scanning."""
    plat = platform or _detect_platform()

    if not plat:
        rprint(fmt.error("Could not auto-detect CI platform."))
        print("Specify one with --platform github|gitlab|circleci", file=sys.stderr)
        raise typer.Exit(code=1)

    valid = ("github", "gitlab", "circleci")
    if plat not in valid:
        rprint(fmt.error(f"Unknown platform: {plat}"))
        print(f"Valid options: {', '.join(valid)}", file=sys.stderr)
        raise typer.Exit(code=1)

    gen_fn, default_path = _GENERATORS[plat]
    content = gen_fn(with_backend)
    out_path = Path(output or default_path)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)

    rprint(fmt.success(f"Generated {plat} CI config at {out_path}"))
    rprint()
    rprint("Next steps:")
    rprint(f"  1. Review the generated file: {out_path}")

    if with_backend:
        secret_instructions = {
            "github": "  2. Add RAFTER_API_KEY to repo Settings > Secrets > Actions",
            "gitlab": "  2. Add RAFTER_API_KEY to Settings > CI/CD > Variables",
            "circleci": "  2. Add RAFTER_API_KEY to project environment variables",
        }
        rprint(secret_instructions[plat])

    step = "3" if with_backend else "2"
    rprint(f"  {step}. Commit and push to trigger the pipeline")
    rprint()
