"""Security policy management commands."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import typer
from rich import print as rprint

from ..core.config_manager import ConfigManager
from ..utils.formatter import fmt

policy_app = typer.Typer(name="policy", help="Security policy management", no_args_is_help=True)


def _generate_claude_config() -> str:
    config = {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [{"type": "command", "command": "rafter hook pretool"}],
                },
                {
                    "matcher": "Write|Edit",
                    "hooks": [{"type": "command", "command": "rafter hook pretool"}],
                },
            ],
        },
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_codex_config() -> str:
    manager = ConfigManager()
    cfg = manager.load_with_policy()
    policy = cfg.agent.command_policy

    blocked = policy.blocked_patterns
    approval = policy.require_approval

    lines = [
        "# Rafter security policy for OpenAI Codex",
        "# Generated by: rafter policy export --format codex",
        "# Docs: https://docs.rafter.so/cli/pretool-hooks",
        "",
    ]

    if blocked:
        lines.append("[rules.blocked]")
        lines.append("# Commands that are always blocked")
        lines.append("patterns = [")
        for p in blocked:
            lines.append(f"    {json.dumps(p)},")
        lines.append("]")
        lines.append("")

    if approval:
        lines.append("[rules.prompt]")
        lines.append("# Commands that require user approval")
        lines.append("patterns = [")
        for p in approval:
            lines.append(f"    {json.dumps(p)},")
        lines.append("]")

    return "\n".join(lines) + "\n"


@policy_app.command("export")
def export_policy(
    format: str = typer.Option(..., "--format", help="Target format: claude or codex"),
    output: str = typer.Option(None, "--output", help="Write to file instead of stdout"),
):
    """Export Rafter policy for agent platforms."""
    if format not in ("claude", "codex"):
        rprint(fmt.error(f"Unknown format: {format}"))
        print("Valid options: claude, codex", file=sys.stderr)
        raise typer.Exit(code=1)

    content = _generate_claude_config() if format == "claude" else _generate_codex_config()

    if output:
        p = Path(output)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        rprint(fmt.success(f"Exported {format} policy to {output}"))
    else:
        sys.stdout.write(content)
