import { Command } from "commander";
import { ConfigManager } from "../../core/config-manager.js";
import { fmt } from "../../utils/formatter.js";

type ExportFormat = "claude" | "codex";

export function createPolicyExportCommand(): Command {
  return new Command("export")
    .description("Export Rafter policy for agent platforms")
    .requiredOption("--format <format>", "Target format: claude or codex")
    .option("--output <path>", "Write to file instead of stdout")
    .action((opts) => {
      const format = opts.format as string;

      if (format !== "claude" && format !== "codex") {
        console.error(fmt.error(`Unknown format: ${format}`));
        console.error("Valid options: claude, codex");
        process.exit(1);
      }

      const content = format === "claude"
        ? generateClaudeConfig()
        : generateCodexConfig();

      if (opts.output) {
        const fs = require("fs");
        const path = require("path");
        const dir = path.dirname(opts.output);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        fs.writeFileSync(opts.output, content, "utf-8");
        console.log(fmt.success(`Exported ${format} policy to ${opts.output}`));
      } else {
        process.stdout.write(content);
      }
    });
}

function generateClaudeConfig(): string {
  const config = {
    hooks: {
      PreToolUse: [
        {
          matcher: "Bash",
          hooks: [{ type: "command", command: "rafter hook pretool" }],
        },
        {
          matcher: "Write|Edit",
          hooks: [{ type: "command", command: "rafter hook pretool" }],
        },
      ],
    },
  };
  return JSON.stringify(config, null, 2) + "\n";
}

function generateCodexConfig(): string {
  const manager = new ConfigManager();
  const cfg = manager.loadWithPolicy();
  const policy = cfg.agent?.commandPolicy;

  const blocked = policy?.blockedPatterns || [];
  const approval = policy?.requireApproval || [];

  let toml = `# Rafter security policy for OpenAI Codex
# Generated by: rafter policy export --format codex
# Docs: https://docs.rafter.so/cli/pretool-hooks

`;

  if (blocked.length > 0) {
    toml += `[rules.blocked]\n`;
    toml += `# Commands that are always blocked\n`;
    toml += `patterns = [\n`;
    for (const p of blocked) {
      toml += `    ${JSON.stringify(p)},\n`;
    }
    toml += `]\n\n`;
  }

  if (approval.length > 0) {
    toml += `[rules.prompt]\n`;
    toml += `# Commands that require user approval\n`;
    toml += `patterns = [\n`;
    for (const p of approval) {
      toml += `    ${JSON.stringify(p)},\n`;
    }
    toml += `]\n`;
  }

  return toml;
}
