import { Command } from "commander";
import fs from "fs";
import path from "path";
import { fmt } from "../../utils/formatter.js";

type CIPlatform = "github" | "gitlab" | "circleci";

export function createCiInitCommand(): Command {
  return new Command("init")
    .description("Generate CI/CD pipeline config for secret scanning")
    .option("--platform <platform>", "CI platform: github, gitlab, circleci (default: auto-detect)")
    .option("--output <path>", "Output file path (default: platform-specific)")
    .option("--with-backend", "Include backend security audit job (requires RAFTER_API_KEY)")
    .action((opts) => {
      const platform = opts.platform || detectPlatform();

      if (!platform) {
        console.error(fmt.error("Could not auto-detect CI platform."));
        console.error("Specify one with --platform github|gitlab|circleci");
        process.exit(1);
      }

      const validPlatforms: CIPlatform[] = ["github", "gitlab", "circleci"];
      if (!validPlatforms.includes(platform)) {
        console.error(fmt.error(`Unknown platform: ${platform}`));
        console.error(`Valid options: ${validPlatforms.join(", ")}`);
        process.exit(1);
      }

      const { content, defaultPath } = generateTemplate(platform as CIPlatform, !!opts.withBackend);
      const outputPath = opts.output || defaultPath;
      const outputDir = path.dirname(outputPath);

      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      fs.writeFileSync(outputPath, content, "utf-8");

      console.log(fmt.success(`Generated ${platform} CI config at ${outputPath}`));
      console.log();
      console.log("Next steps:");
      console.log(`  1. Review the generated file: ${outputPath}`);

      if (opts.withBackend) {
        if (platform === "github") {
          console.log("  2. Add RAFTER_API_KEY to repo Settings > Secrets > Actions");
        } else if (platform === "gitlab") {
          console.log("  2. Add RAFTER_API_KEY to Settings > CI/CD > Variables");
        } else {
          console.log("  2. Add RAFTER_API_KEY to project environment variables");
        }
      }

      console.log(`  ${opts.withBackend ? "3" : "2"}. Commit and push to trigger the pipeline`);
      console.log();
    });
}

function detectPlatform(): CIPlatform | null {
  if (fs.existsSync(".github")) return "github";
  if (fs.existsSync(".gitlab-ci.yml")) return "gitlab";
  if (fs.existsSync(".circleci")) return "circleci";
  return null;
}

function generateTemplate(
  platform: CIPlatform,
  withBackend: boolean,
): { content: string; defaultPath: string } {
  switch (platform) {
    case "github":
      return { content: githubTemplate(withBackend), defaultPath: ".github/workflows/rafter-security.yml" };
    case "gitlab":
      return { content: gitlabTemplate(withBackend), defaultPath: ".gitlab-ci-rafter.yml" };
    case "circleci":
      return { content: circleciTemplate(withBackend), defaultPath: ".circleci/rafter-security.yml" };
  }
}

function githubTemplate(withBackend: boolean): string {
  let yaml = `# Generated by: rafter ci init
name: Rafter Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rafter CLI
        run: npm install -g @rafter-security/cli

      - name: Scan for secrets
        run: rafter agent scan . --quiet
`;

  if (withBackend) {
    yaml += `
  security-audit:
    runs-on: ubuntu-latest
    needs: secret-scan
    steps:
      - uses: actions/checkout@v4

      - name: Install Rafter CLI
        run: npm install -g @rafter-security/cli

      - name: Run security audit
        env:
          RAFTER_API_KEY: \${{ secrets.RAFTER_API_KEY }}
        run: rafter run --format json --quiet
`;
  }

  return yaml;
}

function gitlabTemplate(withBackend: boolean): string {
  let yaml = `# Generated by: rafter ci init
stages:
  - security

secret-scan:
  stage: security
  image: node:20
  script:
    - npm install -g @rafter-security/cli
    - rafter agent scan . --quiet
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
`;

  if (withBackend) {
    yaml += `
security-audit:
  stage: security
  image: node:20
  needs: [secret-scan]
  script:
    - npm install -g @rafter-security/cli
    - rafter run --format json --quiet
  variables:
    RAFTER_API_KEY: $RAFTER_API_KEY
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
`;
  }

  return yaml;
}

function circleciTemplate(withBackend: boolean): string {
  let yaml = `# Generated by: rafter ci init
version: 2.1

jobs:
  secret-scan:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install Rafter CLI
          command: npm install -g @rafter-security/cli
      - run:
          name: Scan for secrets
          command: rafter agent scan . --quiet
`;

  if (withBackend) {
    yaml += `
  security-audit:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install Rafter CLI
          command: npm install -g @rafter-security/cli
      - run:
          name: Run security audit
          command: rafter run --format json --quiet
`;
  }

  yaml += `
workflows:
  security:
    jobs:
      - secret-scan`;

  if (withBackend) {
    yaml += `
      - security-audit:
          requires:
            - secret-scan`;
  }

  yaml += "\n";

  return yaml;
}
